feat(chore): add support for node v18
sourcefuse/loopback4-ratelimiter pull request #111
Opened 2023-05-04 13:42 UTC by RaghavaroraSF

## Description

- Added support for node v18

GH-110

Fixes #110

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-05-08 04:20 UTC, yeshamavani approved these changes

2023-05-08 04:41 UTC, yeshamavani commented
in the repo there as .d.ts and .js index files present 
they are redundant, please remove those files

2023-05-08 04:52 UTC, shubhamp-sf commented on package.json
> -    "node": ">=8.9"
Removing LTS version support should be marked as BREAKING CHANGE.
Refer loopback-next's recent node version commits for more insights.

2023-05-10 04:52 UTC, yeshamavani approved these changes

2023-05-10 04:56 UTC, yeshamavani requested changes
Why is this marked as feature, no new feature is being introduced

2023-05-11 05:13 UTC, yeshamavani commented
After referring loopback decided to go in with feature type

2023-05-11 05:14 UTC, yeshamavani approved these changes

2023-05-11 05:14 UTC, merged

2023-06-07 08:01 UTC, shubhamp-sf commented
:tada: This PR is included in version 5.0.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-ratelimiter/v/5.0.0)
- [GitHub release](https://github.com/sourcefuse/loopback4-ratelimiter/releases/tag/v5.0.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: