feat(providers): add option to apply ratelimiting over single API
sourcefuse/loopback4-ratelimiter pull request #68
Opened 2022-10-12 04:43 UTC by Surbhi-sharma1

GH-46

## Description

Added option to apply ratelimiting over single API.

Fixes # (issue)
GH-46
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Intermediate change (work in progress)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

## Checklist:

- [ ] Performed a self-review of my own code
- [ ] npm test passes on your machine
- [ ] New tests added or existing tests modified to cover all changes
- [ ] Code conforms with the style guide
- [ ] API Documentation in code was updated
- [ ] Any dependent changes have been merged and published in downstream modules

2023-02-21 09:24 UTC, yeshamavani requested changes

2023-02-28 10:35 UTC, Surbhi-sharma1 commented on src/providers/ratelimit-action.provider.ts
> +      return Promise.resolve();
Done

2023-03-10 13:03 UTC, yeshamavani commented on src/providers/ratelimit-action.provider.ts
> +      return Promise.resolve();
Its for the case when enabledByDefault is set to false and also when decorator is not passed over the API

2023-03-10 13:06 UTC, Surbhi-sharma1 commented on src/providers/ratelimit-action.provider.ts
> +      return Promise.resolve();
yes

2023-03-10 13:07 UTC, merged

2023-03-14 13:28 UTC, sfdevops commented
:tada: This PR is included in version 4.3.0 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/loopback4-ratelimiter/v/4.3.0)
- [GitHub release](https://github.com/sourcefuse/loopback4-ratelimiter/releases/tag/v4.3.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: